name: flask ci

on:
  workflow_dispatch:

env:
  IMAGE_NAME: flask-github-actions-cicd
    

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: docker build image
        run: docker build -t $IMAGE_NAME .

      - name: list docker images
        run: docker images

      - name: Docker login
        run: echo "${{secrets.DOCKER_PASSWORD}} " | docker login -u "${{secrets.DOCKER_USER}}" --password-stdin    
          
      - name: docker tag 
        run: docker tag $IMAGE_NAME ${{secrets.DOCKER_USER}}/$IMAGE_NAME:latest

      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER}}/$IMAGE_NAME:latest    

